skip_check_lock
opentrx/mysql pull request #4
Opened 2022-01-17 02:40 UTC by xjlgod

### Description
[refer to this issue](https://github.com/opentrx/seata-golang/issues/96)
I will pull request to seata-golang, too.

### Checklist
- [ ] Code compiles correctly
- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary
- [ ] Added myself / the copyright holder to the AUTHORS file

2022-01-18 00:51 UTC, dk-lockdown commented
这里 skip check lock 只是存了个变量在 applicationDataMap 里，是否还需要在 seata-golang 处跳过锁冲突检查？

2022-01-18 01:52 UTC, xjlgod commented
> 

需要，我不知道对这个skip check lock常量该放哪个文件里，或者名字是否符合项目规范。还需要在 seata-golang 处跳过锁冲突检查的，这个pr我会日后提交

2022-01-18 06:39 UTC, dk-lockdown commented
命名用驼峰吧，go 推荐的命名格式是驼峰

2022-01-18 09:10 UTC, bohehe requested changes

2022-01-18 09:10 UTC, bohehe commented on transaction.go
> +		SKIP_CHECK_LOCK := true
Please use camel format for variables
```suggestion
		skipCheckLock := true
```

2022-01-19 15:33 UTC, xjlgod commented on transaction.go
> +		SKIP_CHECK_LOCK := true
好的，已经改了

2022-01-20 01:51 UTC, bohehe approved these changes

2022-01-20 03:59 UTC, caohdgege commented
> 

1. 考虑到Seata的多语言特性，本身也是存在使用GO的RM，Java的TC。当前Java版本的TC已经加上了对于skip check lock的处理，因此这边做为RM的功能可以先把变量加上。

2022-01-21 01:32 UTC, dk-lockdown commented on transaction.go
> +		SKIP_CHECK_LOCK := true
这个 pr 等 seata-golang 那边代码提交了，我一起合

2022-01-21 01:33 UTC, dk-lockdown commented on transaction.go
> +		SKIP_CHECK_LOCK := true
这个 pr 等 seata-golang 那边提交了，我一起合

2022-01-21 02:25 UTC, xjlgod commented on transaction.go
> +		SKIP_CHECK_LOCK := true
> 这个 pr 等 seata-golang 那边提交了，我一起合

好的，已经提了

2022-01-25 12:09 UTC, wybrobin commented on transaction.go
> +		if !skipCheckLock {
这里是只有skipCheckLock==false的时候才会传递给TC吗？那TC那边取出来的不就只有false的情况？那跟默认的locker.manager.AcquireLock(locks, false)有什么区别呢？我理解是true才传过去吧？

2022-01-25 12:22 UTC, xjlgod commented on transaction.go
> +		if !skipCheckLock {
这里我写错了，已经改过来了。skipCheckLock==true的时候才会传递给TC，false时目前会传nil给tc。

2022-01-26 12:33 UTC, wybrobin commented on transaction.go
> +			if undoLog.BeforeImage == nil || len(undoLog.BeforeImage.Rows) != 0 {
我理解，这段代码的意思是在AT情况下，如果全部都是insert的时候，让TC跳过lock检查，如果理解错了欢迎指正哈。
假设我上面理解的是对的，那么这个||前后是矛盾的。从后面有个break，理解你应该是想当itemsBuffer里只要有一个不是insert，就把skipCheckLock赋值为false，那么这里应该是：
if undoLog.BeforeImage != nil && len(undoLog.BeforeImage.Rows) != 0 {

2022-01-26 12:58 UTC, xjlgod commented on transaction.go
> +			if undoLog.BeforeImage == nil || len(undoLog.BeforeImage.Rows) != 0 {
本来应该是只有len(undoLog.BeforeImage.Rows) != 0这一段。但实际上对于Seata Java来说，如果有undoitem，那他的beforeimage一定不会是null，最多是空列表。但很多测试用例都没设置beforeImgae（在Seata java中经常这样），会造成空指针。因此加上了 undoLog.BeforeImage != nil 这一段，相当于没有设置beforeImage的话，还是会走旧的逻辑，不跳过lock检查。

2022-01-26 13:47 UTC, bohehe commented on transaction.go
> +			if undoLog.BeforeImage == nil || len(undoLog.BeforeImage.Rows) != 0 {
`相当于没有设置beforeImage的话，还是会走旧的逻辑，不跳过lock检查。`
不是很理解为什么没有设置BeforeImage的话，还需要锁检查？

2022-01-26 13:55 UTC, xjlgod commented on transaction.go
> +			if undoLog.BeforeImage == nil || len(undoLog.BeforeImage.Rows) != 0 {
是测试用例中不设置beforeImage的时候走旧的逻辑,业务中是不会出现出现beforeImage为nil的情况的.如果seata-golang这边没有这种测试用例，删掉 undoLog.BeforeImage != nil 这一段即可

2022-01-27 02:19 UTC, dk-lockdown commented on transaction.go
> +			if undoLog.BeforeImage == nil || len(undoLog.BeforeImage.Rows) != 0 {
go 这边的实现，insert 时，beforeImage 默认为空的，此时应该跳过锁冲突检查，所以这里应该采取这个 `undoLog.BeforeImage != nil && len(undoLog.BeforeImage.Rows) != 0` 这个条件判断

2022-01-27 02:19 UTC, wybrobin commented on transaction.go
> +			if undoLog.BeforeImage == nil || len(undoLog.BeforeImage.Rows) != 0 {
如果是undoLog.BeforeImage != nil我就能理解，但是代码里写的是undoLog.BeforeImage == nil，我就不理解了

2022-01-27 03:10 UTC, xjlgod commented on transaction.go
> +			if undoLog.BeforeImage == nil || len(undoLog.BeforeImage.Rows) != 0 {
只是在Seata java测试用例时，会出现beforeImage为nil的情况（这时期望提过锁检查），业务场景下不会出现。go这不会出现，那我改为undoLog.BeforeImage != nil && len(undoLog.BeforeImage.Rows) != 0

2022-01-27 06:10 UTC, wybrobin approved these changes

2022-01-27 06:45 UTC, bohehe approved these changes

2022-01-28 02:05 UTC, merged